default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: github_trending_development
  username: postgres
  password: postgres

test:
  <<: *default
  database: github_trending_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: github_trending_production
  username: github_trending
  password: <%= ENV['GITHUB_TRENDING_DATABASE_PASSWORD'] %>
